// ============================================================
// MUVE QR — In-Memory Demo Store & State Handler
// Fallback state store when Supabase credentials are not connected
// ============================================================

import { QRCodeRow, ScanLogRow, UserRow, AuditLogRow, NotificationRow, AppSettings } from '@/types/database'

export let INITIAL_USERS: UserRow[] = [
  {
    id: 'usr_admin_001',
    full_name: 'System Admin',
    email: 'admin@muveqr.app',
    phone: '+1-555-0100',
    role: 'admin',
    status: 'active',
    avatar_url: null,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_user_001',
    full_name: 'User 01',
    email: 'user01@muveqr.app',
    phone: '+1-555-0101',
    role: 'user',
    status: 'active',
    avatar_url: null,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_user_002',
    full_name: 'User 02',
    email: 'user02@muveqr.app',
    phone: '+1-555-0102',
    role: 'user',
    status: 'active',
    avatar_url: null,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr_user_003',
    full_name: 'User 03',
    email: 'user03@muveqr.app',
    phone: '+1-555-0103',
    role: 'user',
    status: 'active',
    avatar_url: null,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export let INITIAL_QR_CODES: QRCodeRow[] = [
  {
    id: 'qr_001',
    name: 'QR1',
    token: 'MUVEQR-MainEntrance-xK9mP2nQ8vR3tL7w',
    location_name: 'Main Entrance',
    description: 'Primary building entrance scanner point',
    status: 'active',
    latitude: 6.9271,
    longitude: 79.8612,
    geofence_radius: 100,
    created_by: 'usr_admin_001',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'qr_002',
    name: 'QR2',
    token: 'MUVEQR-Office-yJ4nM6pS1uW5eA8d',
    location_name: 'Office',
    description: 'Main executive office area access point',
    status: 'active',
    latitude: 6.9275,
    longitude: 79.8615,
    geofence_radius: null,
    created_by: 'usr_admin_001',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'qr_003',
    name: 'QR3',
    token: 'MUVEQR-Warehouse-zH7kB9qT0iC4fG2x',
    location_name: 'Warehouse',
    description: 'Warehouse loading dock entrance checkpoint',
    status: 'active',
    latitude: 6.9280,
    longitude: 79.8620,
    geofence_radius: 200,
    created_by: 'usr_admin_001',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export let INITIAL_SCANS: ScanLogRow[] = [
  {
    id: 'scan_001',
    user_id: 'usr_user_001',
    qr_id: 'qr_001',
    qr_token: 'MUVEQR-MainEntrance-xK9mP2nQ8vR3tL7w',
    qr_name: 'QR1',
    location_name: 'Main Entrance',
    status: 'success',
    rejection_reason: null,
    latitude: 6.9271,
    longitude: 79.8612,
    device_info: 'iPhone 15 Pro / iOS 17.4',
    scanned_at: new Date(Date.now() - 10 * 60000).toISOString(),
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'scan_002',
    user_id: 'usr_user_002',
    qr_id: 'qr_001',
    qr_token: 'MUVEQR-MainEntrance-xK9mP2nQ8vR3tL7w',
    qr_name: 'QR1',
    location_name: 'Main Entrance',
    status: 'success',
    rejection_reason: null,
    latitude: 6.9271,
    longitude: 79.8612,
    device_info: 'Samsung Galaxy S24 / Android 14',
    scanned_at: new Date(Date.now() - 8 * 60000).toISOString(),
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'scan_003',
    user_id: 'usr_user_001',
    qr_id: 'qr_002',
    qr_token: 'MUVEQR-Office-yJ4nM6pS1uW5eA8d',
    qr_name: 'QR2',
    location_name: 'Office',
    status: 'success',
    rejection_reason: null,
    latitude: 6.9275,
    longitude: 79.8615,
    device_info: 'iPhone 15 Pro / iOS 17.4',
    scanned_at: new Date(Date.now() - 30 * 60000).toISOString(),
    created_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'scan_004',
    user_id: 'usr_user_003',
    qr_id: 'qr_003',
    qr_token: 'MUVEQR-Warehouse-zH7kB9qT0iC4fG2x',
    qr_name: 'QR3',
    location_name: 'Warehouse',
    status: 'success',
    rejection_reason: null,
    latitude: 6.9280,
    longitude: 79.8620,
    device_info: 'Pixel 8 / Android 14',
    scanned_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'scan_005',
    user_id: 'usr_user_002',
    qr_id: 'qr_002',
    qr_token: 'MUVEQR-Office-yJ4nM6pS1uW5eA8d',
    qr_name: 'QR2',
    location_name: 'Office',
    status: 'success',
    rejection_reason: null,
    latitude: null,
    longitude: null,
    device_info: 'Samsung Galaxy S24 / Android 14',
    scanned_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
]

export let INITIAL_NOTIFICATIONS: NotificationRow[] = [
  {
    id: 'notif_001',
    type: 'scan',
    title: 'New Scan Recorded',
    message: 'User 02 scanned QR1 (Main Entrance)',
    scan_id: 'scan_002',
    is_read: false,
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'notif_002',
    type: 'scan',
    title: 'New Scan Recorded',
    message: 'User 01 scanned QR1 (Main Entrance)',
    scan_id: 'scan_001',
    is_read: true,
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
]

export let INITIAL_AUDIT_LOGS: AuditLogRow[] = [
  {
    id: 'audit_001',
    admin_id: 'usr_admin_001',
    admin_name: 'System Admin',
    action: 'qr_created',
    target_type: 'qr_code',
    target_id: 'qr_001',
    target_name: 'QR1',
    details: { location: 'Main Entrance' },
    ip_address: '127.0.0.1',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'audit_002',
    admin_id: 'usr_admin_001',
    admin_name: 'System Admin',
    action: 'user_created',
    target_type: 'user',
    target_id: 'usr_user_001',
    target_name: 'User 01',
    details: { email: 'user01@muveqr.app', role: 'user' },
    ip_address: '127.0.0.1',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
]

export let INITIAL_SETTINGS: AppSettings = {
  org_name: 'MUVE QR Corp',
  timezone: 'UTC',
  date_format: 'DD/MM/YYYY',
  duplicate_scan_cooldown: '5',
  gps_verification_enabled: 'false',
  notification_sound_enabled: 'true',
  logo_url: '',
}
